/**
 * Agenda Alpes-Maritimes — données agrégées
 * Sources : jds.fr, nice.fr, cannes.com, anthea-antibes.fr, univ-cotedazur.fr,
 * mouans-sartoux.net, sortir06.fr, explorenicecotedazur.com, recreanice.fr
 * Coordonnées approximatives des lieux (centres de salles / sites).
 */
window.AGENDA_06 = {
  meta: {
    title: "Côte d'Azur Vivante",
    subtitle: "Spectacles, festivals, conférences & sorties dans les Alpes-Maritimes",
    generatedAt: "2026-10-05T19:20:00+02:00",
    days: [
      "2026-10-02",
      "2026-10-03",
      "2026-10-04",
      "2026-10-05",
      "2026-10-06",
      "2026-10-07",
      "2026-10-08",
      "2026-10-09",
      "2026-10-10",
      "2026-10-11",
    ],
    sources: [
      { name: "JDS Agenda", url: "https://www.jds.fr/alpes-maritimes/agenda/" },
      { name: "Ville de Nice", url: "https://www.nice.fr" },
      { name: "Ville de Cannes", url: "https://www.cannes.com" },
      { name: "anthéa Antibes", url: "https://www.anthea-antibes.fr" },
      { name: "Théâtre National de Nice", url: "https://www.tnn.fr" },
      { name: "Théâtre de Grasse", url: "https://www.theatredegrasse.com" },
      { name: "Univ. Côte d'Azur", url: "https://univ-cotedazur.fr" },
      { name: "Festival du Livre", url: "https://www.lefestivaldulivre.fr" },
      { name: "Mouans-Sartoux", url: "https://www.mouans-sartoux.net" },
      { name: "Sortir06", url: "https://www.sortir06.fr" },
      { name: "Département 06", url: "https://www.departement06.fr" },
      { name: "Agenda culturel 06", url: "https://06.agendaculturel.fr" },
    ],
  },
  categories: {
    theatre: { label: "Théâtre", color: "#F0A06A", icon: "Th" },
    humour: { label: "Humour", color: "#F4C95F", icon: "Hu" },
    danse: { label: "Danse", color: "#E8A0BF", icon: "Da" },
    concert: { label: "Concert", color: "#7EC8E3", icon: "Co" },
    festival: { label: "Festival", color: "#5EEAD4", icon: "Fe" },
    conference: { label: "Conférence", color: "#9BB8C9", icon: "Cf" },
    cinema: { label: "Cinéma", color: "#E89AA8", icon: "Ci" },
    sport: { label: "Sport", color: "#86EFAC", icon: "Sp" },
    famille: { label: "Famille", color: "#FDBA74", icon: "Fa" },
    expo: { label: "Expo / marché", color: "#94A3B8", icon: "Ex" },
    soiree: { label: "Soirée", color: "#FB7185", icon: "So" },
    gastronomie: { label: "Gastronomie", color: "#FCD34D", icon: "Ga" },
  },
  events: [
    // ——— Vendredi 2 octobre ———
    {
      id: "fds-banquet",
      title: "Nuit de la Science — Banquet des arts et des sciences",
      days: ["2026-10-02"],
      time: "18h30–21h",
      category: "festival",
      city: "Nice",
      venue: "Parc Valrose",
      address: "28 avenue Valrose, Nice",
      lat: 43.7156,
      lng: 7.2658,
      price: "Gratuit (sur inscription)",
      free: true,
      description: "Ouverture « Saveurs Savantes » : banquet, théâtre à la carte, dégustations scientifiques. Tram Valrose-Université.",
      source: "univ-cotedazur.fr",
      url: "https://univ-cotedazur.fr/festival-des-sciences/festival-des-sciences-de-nice-2026",
    },
    {
      id: "hollande-mouans",
      title: "Grand entretien — François Hollande",
      days: ["2026-10-02"],
      time: "16h30",
      category: "conference",
      city: "Mouans-Sartoux",
      venue: "Festival du Livre — Scène littéraire",
      address: "Mouans-Sartoux",
      lat: 43.6212,
      lng: 6.972,
      price: "Gratuit (places limitées)",
      free: true,
      description: "Présentation de Unir — nouveau monde, nouvelle gauche, suivie de dédicaces 17h–19h.",
      source: "lefestivaldulivre.fr",
      url: "https://www.lefestivaldulivre.fr",
    },
    {
      id: "livre-mouans-2",
      title: "39e Festival du Livre",
      days: ["2026-10-02", "2026-10-03", "2026-10-04"],
      time: "10h–19h",
      category: "festival",
      city: "Mouans-Sartoux",
      venue: "Centre-ville & La Strada",
      address: "Mouans-Sartoux",
      lat: 43.6205,
      lng: 6.9712,
      price: "Gratuit",
      free: true,
      description: "Rencontres d'auteurs, débats, jeunesse, BD, spectacles, concerts et cinéma. Un des grands RDV livres du Sud.",
      source: "mouans-sartoux.net",
      url: "https://www.mouans-sartoux.net/evenements/le-festival-du-livre/",
    },
    {
      id: "anthea-millepied-2",
      title: "Du bout des lèvres — Benjamin Millepied",
      days: ["2026-10-02", "2026-10-03"],
      time: "20h30",
      category: "danse",
      city: "Antibes",
      venue: "anthéa — salle Jacques Audiberti",
      address: "260 av. Jules Grec, Antibes",
      lat: 43.5948,
      lng: 7.1105,
      price: "Tarifs anthéa",
      free: false,
      description: "Ballet inspiré des chansons de Barbara. Neuf danseurs, drapés blancs, voix de Barbara devenue mouvement.",
      source: "anthea-antibes.fr",
      url: "https://www.anthea-antibes.fr/fr/spectacles/saison-2026-2027/privilege-spectacle-vivant/du-bout-des-levres",
    },
    {
      id: "barbara-chant",
      title: "Le tour de chant de Barbara",
      days: ["2026-10-02", "2026-10-03", "2026-10-04"],
      time: "Ven 19h · Sam 16h & 19h · Dim 17h",
      category: "concert",
      city: "Antibes",
      venue: "anthéa — salle Pierre Vaneck",
      address: "260 av. Jules Grec, Antibes",
      lat: 43.5952,
      lng: 7.1098,
      price: "Tarifs anthéa",
      free: false,
      description: "Romane Minguet & Roland Romanelli — avant le ballet Millepied, les plus belles compositions de Barbara.",
      source: "anthea-antibes.fr",
      url: "https://www.anthea-antibes.fr/fr/spectacles/saison-2026-2027/tout-le-spectacle-vivant/le-tour-de-chant-de-barbara",
    },
    {
      id: "cineroman",
      title: "Festival CinéRoman (clôture le 3)",
      days: ["2026-10-02", "2026-10-03"],
      time: "Journée / soirée",
      category: "cinema",
      city: "Nice",
      venue: "Pathé Gare du Sud, Rialto, Belmondo…",
      address: "Nice",
      lat: 43.7112,
      lng: 7.2618,
      price: "Selon séances",
      free: false,
      description: "Adaptations littéraires à l'écran, avant-premières et rencontres. Clôture samedi 3 octobre.",
      source: "nice.fr",
      url: "https://www.nice.fr/festival-cineroman/",
    },
    {
      id: "imperiales-2",
      title: "Journées Impériales — ouverture",
      days: ["2026-10-02"],
      time: "17h30",
      category: "festival",
      city: "Nice",
      venue: "Villa Masséna & CUM",
      address: "65 rue de France / 65 promenade des Anglais",
      lat: 43.695,
      lng: 7.2628,
      price: "Gratuit",
      free: true,
      description: "Histoire, reconstitutions et débats autour des Empires français et des coups d'État.",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/manifestations/les-journees-imperiales-a-nice-histoire-spectacles-et-debats-autour-des-empires-francais-1768058_A",
    },

    // ——— Samedi 3 octobre ———
    {
      id: "fds-nice-3",
      title: "Festival des Sciences — Saveurs Savantes",
      days: ["2026-10-03", "2026-10-04"],
      time: "10h–18h",
      category: "festival",
      city: "Nice",
      venue: "Parc Valrose",
      address: "28 avenue Valrose, Nice",
      lat: 43.7156,
      lng: 7.2658,
      price: "Gratuit",
      free: true,
      description: "Village des sciences : stands, ateliers, conférences. Tram L1 Valrose-Université.",
      source: "univ-cotedazur.fr",
      url: "https://univ-cotedazur.fr/festival-des-sciences/festival-des-sciences-de-nice-2026",
    },
    {
      id: "aleveque-mouans",
      title: "Christophe Alévêque — revue de presse",
      days: ["2026-10-03"],
      time: "15h30",
      category: "humour",
      city: "Mouans-Sartoux",
      venue: "Festival du Livre — La Strada",
      address: "201 av. de Cannes, Mouans-Sartoux",
      lat: 43.6195,
      lng: 6.9735,
      price: "Selon billetterie festival",
      free: false,
      description: "Spectacle / revue de presse au 39e Festival du Livre.",
      source: "lefestivaldulivre.fr",
      url: "https://www.lefestivaldulivre.fr/spectacles/",
    },
    {
      id: "malzieu-mouans",
      title: "Concert-lecture — Mathias Malzieu",
      days: ["2026-10-03"],
      time: "16h",
      category: "concert",
      city: "Mouans-Sartoux",
      venue: "Festival du Livre — La Strada",
      address: "201 av. de Cannes, Mouans-Sartoux",
      lat: 43.6192,
      lng: 6.9738,
      price: "Dès 5 €",
      free: false,
      description: "Un Noël sur la lune avec Mike Ponton — dès 6 ans.",
      source: "lefestivaldulivre.fr",
      url: "https://www.lefestivaldulivre.fr/spectacles/",
    },
    {
      id: "prom14-mouans",
      title: "Prom 14 — Cie Dire-Dire",
      days: ["2026-10-03"],
      time: "20h",
      category: "theatre",
      city: "Mouans-Sartoux",
      venue: "Festival du Livre — La Strada",
      address: "201 av. de Cannes, Mouans-Sartoux",
      lat: 43.619,
      lng: 6.974,
      price: "12–20 €",
      free: false,
      description: "D’après Thierry Vimal, mise en scène Jonathan Gensburger — déconseillé aux jeunes.",
      source: "lefestivaldulivre.fr",
      url: "https://www.lefestivaldulivre.fr/spectacles/",
    },
    {
      id: "village-sciences-vl",
      title: "Village des Sciences",
      days: ["2026-10-03", "2026-10-04"],
      time: "Sam 13h30–19h · Dim 10h–18h",
      category: "festival",
      city: "Villeneuve-Loubet",
      venue: "Village des Sciences",
      address: "Villeneuve-Loubet",
      lat: 43.6395,
      lng: 7.1265,
      price: "Gratuit",
      free: true,
      description: "Stands, films, conférences, robotique, ITER, paléontologie… Cadre Fête de la Science.",
      source: "univ-cotedazur.fr",
      url: "https://science-societe.univ-cotedazur.fr/fete-de-la-science/coordination-fete-de-la-science-06/evenements-grand-public/village-des-sciences-de-villeneuve-loubet-grand-public-3",
    },
    {
      id: "imperiales-3",
      title: "Journées Impériales",
      days: ["2026-10-03", "2026-10-04"],
      time: "Dès 10h",
      category: "festival",
      city: "Nice",
      venue: "Villa Masséna & CUM",
      address: "65 promenade des Anglais",
      lat: 43.6946,
      lng: 7.2552,
      price: "Gratuit",
      free: true,
      description: "Reconstitutions, mode Empire, conférences. Bal d'automne 17h30 (sam.). Spectacle historique dim. 16h.",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/manifestations/les-journees-imperiales-a-nice-histoire-spectacles-et-debats-autour-des-empires-francais-1768058_A",
    },
    {
      id: "entretien-empires",
      title: "Grand entretien — Empires & coups d'État",
      days: ["2026-10-03"],
      time: "11h",
      category: "conference",
      city: "Nice",
      venue: "CUM",
      address: "65 promenade des Anglais, Nice",
      lat: 43.6944,
      lng: 7.2548,
      price: "Gratuit",
      free: true,
      description: "Arthur Chevallier & Xavier Mauduit. Tables rondes l'après-midi (14h15, 15h45).",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/manifestations/les-journees-imperiales-a-nice-histoire-spectacles-et-debats-autour-des-empires-francais-1768058_A",
    },
    {
      id: "mobilite-douce",
      title: "Journée de la Mobilité Douce",
      days: ["2026-10-03"],
      time: "10h–17h",
      category: "famille",
      city: "Nice",
      venue: "Promenade du Paillon",
      address: "Promenade du Paillon, Nice",
      lat: 43.7008,
      lng: 7.2715,
      price: "Gratuit",
      free: true,
      description: "Ateliers, bourse aux vélos, infos transports doux. Maison de l'Environnement.",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/manifestations/journee-de-la-mobilite-douce-a-nice-sur-la-promenade-du-paillon-1778528_A",
    },
    {
      id: "happy-inde",
      title: "Happy Inde #4 — ouverture",
      days: ["2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10"],
      time: "Dès 3 oct. (jusqu'au 10)",
      category: "festival",
      city: "Nice",
      venue: "Espace Magnan",
      address: "31 rue Louis de Coppet, Nice",
      lat: 43.6988,
      lng: 7.2495,
      price: "Selon programme",
      free: false,
      description: "Festival autour du Rajasthan : concerts, danse, expos, ateliers famille à Magnan et ailleurs.",
      source: "explorenicecotedazur.com",
      url: "https://www.explorenicecotedazur.com/en/event/festival-happy-inde-4e-edition/",
    },
    {
      id: "ufctc",
      title: "Un Festival C'est Trop Court !",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09"],
      time: "Journée → 20h+",
      category: "cinema",
      city: "Nice",
      venue: "Le 109 & Cinéma Belmondo",
      address: "Le 109, Nice",
      lat: 43.6798,
      lng: 7.2112,
      price: "~10 € soirées",
      free: false,
      description: "Compétitions courts métrages, Pitch it ! / Scopitone en soirée.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "le-clan",
      title: "Le Clan",
      days: ["2026-10-03"],
      time: "20h",
      category: "theatre",
      city: "Nice",
      venue: "Théâtre de la Tour",
      address: "63 bd Gorbella, Nice",
      lat: 43.7286,
      lng: 7.2608,
      price: "14–15,50 €",
      free: false,
      description: "Comédie corse hilarante : un clan de voyous pieds nickelés, un kidnapping de star… fiasco en vue ?",
      source: "nice.fr",
      url: "https://www.nice.fr/agenda/le-clan/20261003-2000/",
    },
    {
      id: "pablo-mira",
      title: "Pablo Mira — humour",
      days: ["2026-10-03"],
      time: "20h30",
      category: "humour",
      city: "Nice",
      venue: "Théâtre de la Cité",
      address: "3 rue Paganini, Nice",
      lat: 43.7012,
      lng: 7.2668,
      price: "Billetterie sur place",
      free: false,
      description: "Stand-up au Théâtre de la Cité, cœur de Nice.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "nadia-richard",
      title: "Nadia Richard — Pourquoi j'attire les connards ?",
      days: ["2026-10-03"],
      time: "20h30",
      category: "humour",
      city: "Nice",
      venue: "Théâtre Forum Jorge François",
      address: "Nice",
      lat: 43.7102,
      lng: 7.2625,
      price: "À partir de 26 €",
      free: false,
      description: "One-woman-show sur relations toxiques et confiance en soi (~60–70 min).",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/spectacles/humour/nadia-richard-pourquoi-j-attire-les-connards-tournee-1590650_A",
    },
    {
      id: "apero-frenchy",
      title: "L'Apéro des Frenchy VS No Diggity",
      days: ["2026-10-03"],
      time: "18h–23h30",
      category: "soiree",
      city: "Nice",
      venue: "Allianz Riviera",
      address: "Boulevard des Jardiniers, Nice",
      lat: 43.7051,
      lng: 7.1926,
      price: "Selon billetterie · +18 ans",
      free: false,
      description: "Deux scènes, DJ, food — grosse soirée ouverte à l'Allianz Riviera.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "colloque-ia-menton",
      title: "Colloque IA : opportunités ou dangers ?",
      days: ["2026-10-03"],
      time: "14h15",
      category: "conference",
      city: "Menton",
      venue: "Palais de l'Europe",
      address: "Palais de l'Europe, Menton",
      lat: 43.7751,
      lng: 7.4971,
      price: "Gratuit — résa 04 92 10 50 16",
      free: true,
      description: "Avec Laurent Alexandre et invités — débat grand public sur l'intelligence artificielle.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "fausse-note-valbonne",
      title: "Fausse note",
      days: ["2026-10-03"],
      time: "21h",
      category: "theatre",
      city: "Valbonne",
      venue: "Petit Théâtre de Valbonne",
      address: "Valbonne",
      lat: 43.642,
      lng: 7.0085,
      price: "Selon billetterie",
      free: false,
      description: "Comédie au Petit Théâtre — soirée intimiste en arrière-pays.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "florian-lex",
      title: "Florian Lex — Imparfaits",
      days: ["2026-10-03"],
      time: "20h30",
      category: "humour",
      city: "Nice",
      venue: "Théâtre Lino Ventura",
      address: "Nice",
      lat: 43.7055,
      lng: 7.2648,
      price: "À partir de 40 €",
      free: false,
      description: "One-man-show : le Français qui râle, la raclette et les embrouilles du quotidien.",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/spectacles/humour/florian-lex-imparfaits-tournee-1269375_A",
    },
    {
      id: "tempete-mentale",
      title: "Tempête Mentale — Patrick Martin",
      days: ["2026-10-03"],
      time: "21h",
      category: "theatre",
      city: "Nice",
      venue: "Théâtre l'Alphabet",
      address: "19 rue Delille, Nice",
      lat: 43.7016,
      lng: 7.2712,
      price: "~12 €",
      free: false,
      description: "Mentalisme : pensées croisées, choix devinés, connexions invisibles.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "nouveaux-sorciers",
      title: "Les nouveaux sorciers",
      days: ["2026-10-03"],
      time: "Après-midi / soir",
      category: "famille",
      city: "Nice",
      venue: "Théâtre l'Alphabet",
      address: "19 rue Delille, Nice",
      lat: 43.7014,
      lng: 7.2708,
      price: "Selon séance",
      free: false,
      description: "Spectacle de magie pour apprentis sorciers dès 4 ans.",
      source: "recreanice.fr",
      url: "https://recreanice.fr/agenda-des-sorties",
    },
    {
      id: "elephant",
      title: "Un éléphant ça trompe… éternuement !",
      days: ["2026-10-03"],
      time: "10h30",
      category: "famille",
      city: "Nice",
      venue: "Théâtre l'Alphabet",
      address: "19 rue Delille, Nice",
      lat: 43.7018,
      lng: 7.2715,
      price: "Dès ~10 €",
      free: false,
      description: "Spectacle jeune public (en série jusqu'en décembre).",
      source: "festscanner.com",
      url: "https://festscanner.com/fr/event/un-elephant-ca-trompe-eternuement-nice-2026-10",
    },
    {
      id: "djadja",
      title: "Djadja & Dinaz — Terminal 7",
      days: ["2026-10-03"],
      time: "20h",
      category: "concert",
      city: "Nice",
      venue: "Palais Nikaïa",
      address: "163 bd René Cassin, Nice",
      lat: 43.6762,
      lng: 7.1998,
      price: "40–65 €",
      free: false,
      description: "Rap mélodique — tournée 2026 au plus grand palais de la région.",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/concerts/rap/djadja-et-dinaz-tournee-1082627_A",
    },
    {
      id: "opera-bastringue",
      title: "Opéra Bastringue",
      days: ["2026-10-03"],
      time: "Soirée",
      category: "concert",
      city: "Nice",
      venue: "La Semeuse",
      address: "Centre Culturel La Providence, Nice",
      lat: 43.7148,
      lng: 7.2545,
      price: "Selon billetterie",
      free: false,
      description: "Conférence-spectacle décalée pour néophytes et amoureux du lyrique.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "octobre-rose",
      title: "Ensemble pour Octobre Rose",
      days: ["2026-10-03"],
      time: "Journée",
      category: "conference",
      city: "Nice",
      venue: "Nice",
      address: "Nice",
      lat: 43.7025,
      lng: 7.2685,
      price: "Gratuit",
      free: true,
      description: "Prévention, Tai Chi, Qi Gong et solidarité.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "monster-truck",
      title: "Monster Truck & Hells Driver",
      days: ["2026-10-03", "2026-10-04"],
      time: "Sam 14h30 & 20h · Dim 14h30",
      category: "famille",
      city: "Nice",
      venue: "MIN d'Azur — porte B",
      address: "19 bd du Mercantour, Nice",
      lat: 43.6895,
      lng: 7.1865,
      price: "18 € / 12 € enfant",
      free: false,
      description: "Cascades et monster trucks — billetterie sur place (guichets 2h avant).",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/spectacles/monster-truck-et-cascades-a-nice-danglade-show-hells-driver-3-au-18-octobre-2026-1743087_A",
    },
    {
      id: "rourou",
      title: "Les aventures de Rourou l'écureuil",
      days: ["2026-10-03", "2026-10-04", "2026-10-05"],
      time: "Selon séances",
      category: "famille",
      city: "Nice",
      venue: "Théâtre l'Impertinent",
      address: "Nice",
      lat: 43.6982,
      lng: 7.2755,
      price: "Selon billetterie",
      free: false,
      description: "Quand la peluche de Sacha prend vie — aventure jeune public jusqu'au 24 oct.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "couffin",
      title: "Trois Hommes et un Couffin",
      days: ["2026-10-03"],
      time: "16h30 & 20h30",
      category: "theatre",
      city: "Cannes",
      venue: "Théâtre Alexandre III",
      address: "19 bd Alexandre III, Cannes",
      lat: 43.5518,
      lng: 7.0172,
      price: "15 €",
      free: false,
      description: "Comédie de Coline Serreau adaptée au théâtre. Résa 06 08 18 13 58.",
      source: "cannes.com",
      url: "https://www.cannes.com/fr/agenda/annee-2026/octobre/trois-hommes-et-un-couffin.html",
    },
    {
      id: "offenbach-cannes",
      title: "Offenbach — Du rire aux rêves",
      days: ["2026-10-03"],
      time: "18h30",
      category: "concert",
      city: "Cannes",
      venue: "Église Holy Trinity",
      address: "2 av. Branly, Cannes",
      lat: 43.5508,
      lng: 7.0198,
      price: "20 €",
      free: false,
      description: "Opér'Azur : de l'opérette pétillante aux Contes d'Hoffmann.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "concert-ombres",
      title: "Concert des Ombres",
      days: ["2026-10-03"],
      time: "19h–20h15",
      category: "concert",
      city: "Cannes",
      venue: "Théâtre de la Licorne",
      address: "Cannes La Bocca",
      lat: 43.5512,
      lng: 6.9815,
      price: "Gratuit",
      free: true,
      description: "Violon, violoncelle, piano — univers mystérieux entre classique et cinéma fantastique. Déguisement bienvenu !",
      source: "jds.fr",
      url: "https://www.jds.fr/cannes/concerts/musique-classique/concert-des-ombres-1731085_A",
    },
    {
      id: "as-cannes",
      title: "AS Cannes – Quevilly (National 1)",
      days: ["2026-10-03"],
      time: "Match du jour",
      category: "sport",
      city: "Cannes",
      venue: "Stade Pierre de Coubertin",
      address: "Cannes",
      lat: 43.5535,
      lng: 7.0115,
      price: "Billetterie club",
      free: false,
      description: "Football National 1 à domicile.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "gabrielle",
      title: "Gabrielle au naturel — Gabrielle Giraud",
      days: ["2026-10-02", "2026-10-03"],
      time: "Selon séances",
      category: "humour",
      city: "Antibes",
      venue: "Théâtre le Tribunal",
      address: "Antibes",
      lat: 43.5808,
      lng: 7.1252,
      price: "Selon billetterie",
      free: false,
      description: "One-woman-show : personnages mythiques et humour.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "diner-belles-rives",
      title: "Dîner à quatre mains — La Passagère",
      days: ["2026-10-03"],
      time: "20h",
      category: "gastronomie",
      city: "Juan-les-Pins",
      venue: "Hôtel Belles Rives",
      address: "Juan-les-Pins, Antibes",
      lat: 43.5652,
      lng: 7.1148,
      price: "Menu gastronomique",
      free: false,
      description: "Dîner à quatre mains au restaurant La Passagère.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "tiroir-woody",
      title: "Le tiroir de Woody Allen",
      days: ["2026-10-03", "2026-10-04"],
      time: "21h",
      category: "theatre",
      city: "Valbonne",
      venue: "Petit Théâtre de Valbonne",
      address: "Valbonne",
      lat: 43.6418,
      lng: 7.0088,
      price: "Selon billetterie",
      free: false,
      description: "Comédie déjantée : quatre comédiens, douze personnages, satire télé.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "madame-marguerite",
      title: "Madame Marguerite",
      days: ["2026-10-03", "2026-10-04", "2026-10-05"],
      time: "Selon séances",
      category: "theatre",
      city: "Valbonne",
      venue: "Petit Théâtre de Valbonne",
      address: "Valbonne",
      lat: 43.6414,
      lng: 7.0092,
      price: "Selon billetterie",
      free: false,
      description: "Pièce culte : leçons truculentes et réflexion — en série jusqu'en décembre.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "coucou-brassens",
      title: "Coucou Brassens",
      days: ["2026-10-03"],
      time: "Soirée",
      category: "concert",
      city: "Saint-Vallier-de-Thiey",
      venue: "Espace du Thiey",
      address: "Saint-Vallier-de-Thiey",
      lat: 43.6985,
      lng: 6.8475,
      price: "Selon billetterie",
      free: false,
      description: "Mélodies du Maître, nouvelles paroles — spectacle musical.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "signe-sacha",
      title: "Signé Sacha",
      days: ["2026-10-03"],
      time: "Soirée",
      category: "theatre",
      city: "Beaulieu-sur-Mer",
      venue: "Casino de Beaulieu",
      address: "Beaulieu-sur-Mer",
      lat: 43.7072,
      lng: 7.3318,
      price: "Selon billetterie",
      free: false,
      description: "Sacha Guitry, les femmes et les amants — comédie au Casino.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "french-riviera-open",
      title: "French Riviera Open (tennis)",
      days: ["2026-10-03", "2026-10-04"],
      time: "Journée (jusqu'au 4)",
      category: "sport",
      city: "Biot",
      venue: "Mouratoglou Hotel & Resort",
      address: "Biot",
      lat: 43.6285,
      lng: 7.0985,
      price: "Billetterie tournoi",
      free: false,
      description: "Grand tournoi de tennis sur la Côte.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "transvesubienne",
      title: "Transvésubienne (trail / VTT)",
      days: ["2026-10-03", "2026-10-04"],
      time: "Départs dès le matin",
      category: "sport",
      city: "Valdeblore",
      venue: "Colmiane → Nice",
      address: "Valdeblore / La Colmiane",
      lat: 44.0685,
      lng: 7.1885,
      price: "Inscription course",
      free: false,
      description: "Trail samedi, VTT dimanche — sentiers mythiques des Alpes-Maritimes.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "mouette",
      title: "La Mouette",
      days: ["2026-10-03", "2026-10-04", "2026-10-05"],
      time: "Selon séances",
      category: "theatre",
      city: "Antibes",
      venue: "Antibea Théâtre",
      address: "Antibes",
      lat: 43.5825,
      lng: 7.1225,
      price: "Selon billetterie",
      free: false,
      description: "Tchekhov — amour, art et sentiments non partagés (en série).",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },

    // ——— Dimanche 4 octobre ———
    {
      id: "fete-terroir",
      title: "Fête du Terroir",
      days: ["2026-10-04"],
      time: "10h–18h",
      category: "famille",
      city: "Saint-Laurent-du-Var",
      venue: "Av. du 11 Novembre & Parc Layet",
      address: "Saint-Laurent-du-Var",
      lat: 43.6705,
      lng: 7.1885,
      price: "Gratuit",
      free: true,
      description: "Marché provençal, parade Belle Époque 10h30, ferme pédagogique, animations famille.",
      source: "sortir06.fr",
      url: "https://www.sortir06.fr/agenda/par-mois/dimanche-4-octobre-2026-fete-du-terroir/",
    },
    {
      id: "offenbach-cagnes",
      title: "Offenbach — Du rire aux rêves",
      days: ["2026-10-04"],
      time: "16h",
      category: "concert",
      city: "Cagnes-sur-Mer",
      venue: "Espace Val Fleuri",
      address: "Cagnes-sur-Mer",
      lat: 43.6638,
      lng: 7.1485,
      price: "15–20 €",
      free: false,
      description: "Opér'Azur — 20 artistes, opérette puis Contes d'Hoffmann. Résa contact@operazur.fr",
      source: "tourisme.cagnes.fr",
      url: "https://tourisme.cagnes.fr/agenda/concert-offenbach-du-rire-aux-reves-4-octobre-2026/",
    },
    {
      id: "balavoine",
      title: "Hommage à Balavoine — Patrice Carmona",
      days: ["2026-10-04"],
      time: "19h",
      category: "concert",
      city: "Cannes",
      venue: "Palais des Festivals",
      address: "Cannes",
      lat: 43.5528,
      lng: 7.0178,
      price: "Selon billetterie",
      free: false,
      description: "Spectacle musical hommage à Daniel Balavoine.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/dimanche-4-octobre-2026-4-10-2026_JPJ",
    },
    {
      id: "imperiales-spectacle",
      title: "L'apogée de la France Impériale",
      days: ["2026-10-04"],
      time: "16h",
      category: "theatre",
      city: "Nice",
      venue: "CUM / Journées Impériales",
      address: "65 promenade des Anglais, Nice",
      lat: 43.6945,
      lng: 7.2555,
      price: "Gratuit",
      free: true,
      description: "Spectacle historique, lyrique et chorégraphique — Wagram à Moscou (1809–1812).",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/manifestations/les-journees-imperiales-a-nice-histoire-spectacles-et-debats-autour-des-empires-francais-1768058_A",
    },

    // ——— Lundi 5 octobre ———
    {
      id: "faites-sciences-mouans",
      title: "Faites des Sciences à Mouans-Sartoux",
      days: ["2026-10-05"],
      time: "Dès le 5 (jusqu'au 10)",
      category: "festival",
      city: "Mouans-Sartoux",
      venue: "Ville & médiathèque",
      address: "Mouans-Sartoux",
      lat: 43.6198,
      lng: 6.9705,
      price: "Gratuit / selon anim.",
      free: true,
      description: "Projections, apéro'Science, escape game, ateliers — suite Fête de la Science.",
      source: "fetedelascience.fr",
      url: "https://www.fetedelascience.fr/faites-des-sciences-mouans-sartoux-2026",
    },
    {
      id: "ufctc-109-experience",
      title: "UFCTC — Compétition Expérience #2",
      days: ["2026-10-05"],
      time: "16h",
      category: "cinema",
      city: "Nice",
      venue: "Le 109",
      address: "89 route de Turin, Nice",
      lat: 43.7198,
      lng: 7.2765,
      price: "Pass festival 35 € / 25 € étudiants",
      free: false,
      description: "26e Un Festival C'est Trop Court ! — 19 films dans la sélection Expérience. Thème 2026 : Voyageur en Transe.",
      source: "nicemag.fr",
      url: "https://www.nicemag.fr/article/7880/nice-sept-rendez-vous-ce-lundi-pour-un-festival-c-est-trop-court",
    },
    {
      id: "ufctc-belmondo-eu6",
      title: "UFCTC — Compétition européenne #6",
      days: ["2026-10-05"],
      time: "16h30",
      category: "cinema",
      city: "Nice",
      venue: "Cinéma Jean-Paul Belmondo",
      address: "1 place Alexis Besson, Nice",
      lat: 43.7036,
      lng: 7.2618,
      price: "Pass festival",
      free: false,
      description: "Programme 6 de la compétition européenne — courts-métrages.",
      source: "nicemag.fr",
      url: "https://www.nicemag.fr/article/7880/nice-sept-rendez-vous-ce-lundi-pour-un-festival-c-est-trop-court",
    },
    {
      id: "ufctc-109-courtsdici",
      title: "UFCTC — Courts d'ici #3",
      days: ["2026-10-05"],
      time: "18h",
      category: "cinema",
      city: "Nice",
      venue: "Le 109",
      address: "89 route de Turin, Nice",
      lat: 43.7198,
      lng: 7.2765,
      price: "Pass festival",
      free: false,
      description: "Sélection cinéastes de la Région Sud et de Corse.",
      source: "nicemag.fr",
      url: "https://www.nicemag.fr/article/7880/nice-sept-rendez-vous-ce-lundi-pour-un-festival-c-est-trop-court",
    },
    {
      id: "ufctc-cine-sante",
      title: "UFCTC — Ciné santé (entrée libre)",
      days: ["2026-10-05"],
      time: "18h30",
      category: "cinema",
      city: "Nice",
      venue: "Cinéma Jean-Paul Belmondo",
      address: "1 place Alexis Besson, Nice",
      lat: 43.7036,
      lng: 7.2618,
      price: "Gratuit",
      free: true,
      description: "Quatre courts-métrages — séance annoncée en entrée libre.",
      source: "nicemag.fr",
      url: "https://www.nicemag.fr/article/7880/nice-sept-rendez-vous-ce-lundi-pour-un-festival-c-est-trop-court",
    },
    {
      id: "ufctc-varietes-eu7",
      title: "UFCTC — Compétition européenne #7",
      days: ["2026-10-05"],
      time: "19h",
      category: "cinema",
      city: "Nice",
      venue: "Cinéma Variétés",
      address: "7 boulevard Victor Hugo, Nice",
      lat: 43.7004,
      lng: 7.2662,
      price: "Pass festival",
      free: false,
      description: "Programme 7 au Variétés — soirée courts européens.",
      source: "nicemag.fr",
      url: "https://www.nicemag.fr/article/7880/nice-sept-rendez-vous-ce-lundi-pour-un-festival-c-est-trop-court",
    },
    {
      id: "ufctc-belmondo-courtsdici",
      title: "UFCTC — Courts d'ici (soir)",
      days: ["2026-10-05"],
      time: "20h30",
      category: "cinema",
      city: "Nice",
      venue: "Cinéma Jean-Paul Belmondo",
      address: "1 place Alexis Besson, Nice",
      lat: 43.7036,
      lng: 7.2618,
      price: "Pass festival",
      free: false,
      description: "Retour de la sélection régionale au Belmondo.",
      source: "nicemag.fr",
      url: "https://www.nicemag.fr/article/7880/nice-sept-rendez-vous-ce-lundi-pour-un-festival-c-est-trop-court",
    },
    {
      id: "ufctc-varietes-eu-nuit",
      title: "UFCTC — Compétition européenne (clôture du soir)",
      days: ["2026-10-05"],
      time: "21h",
      category: "cinema",
      city: "Nice",
      venue: "Cinéma Variétés",
      address: "7 boulevard Victor Hugo, Nice",
      lat: 43.7004,
      lng: 7.2662,
      price: "Pass festival",
      free: false,
      description: "Dernière séance européenne de la journée au Variétés.",
      source: "nicemag.fr",
      url: "https://www.nicemag.fr/article/7880/nice-sept-rendez-vous-ce-lundi-pour-un-festival-c-est-trop-court",
    },
    {
      id: "cinema-amateur-cannes",
      title: "Le cinéma amateur sur grand écran",
      days: ["2026-10-05"],
      time: "17h30–20h",
      category: "cinema",
      city: "Cannes",
      venue: "Maison des Associations",
      address: "1 avenue des Broussailles, Cannes",
      lat: 43.5578,
      lng: 7.0125,
      price: "Gratuit",
      free: true,
      description: "Soirée projection du Ciné Caméra Club de Cannes — 06 15 34 08 09.",
      source: "cannes.com",
      url: "https://www.cannes.com/fr/agenda/annee-2026/octobre/le-cinema-amateur-sur-grand-ecran-05-10.html",
    },
    {
      id: "marche-borrigo",
      title: "Marché du Borrigo",
      days: ["2026-10-05"],
      time: "8h–13h30",
      category: "expo",
      city: "Menton",
      venue: "Quartier Borrigo",
      address: "Menton",
      lat: 43.7848,
      lng: 7.4948,
      price: "Gratuit",
      free: true,
      description: "Marché alimentaire et vestimentaire du lundi — proximité de quartier.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/lundi-5-octobre-2026-5-10-2026_JPJ",
    },
    {
      id: "marche-pre-du-lac",
      title: "Marché du Pré du Lac",
      days: ["2026-10-05"],
      time: "Jusqu'à 13h",
      category: "expo",
      city: "Châteauneuf-Grasse",
      venue: "Parking place des Pins",
      address: "Châteauneuf-Grasse",
      lat: 43.6755,
      lng: 6.9748,
      price: "Gratuit",
      free: true,
      description: "Marché du lundi matin en pays grassois.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/lundi-5-octobre-2026-5-10-2026_JPJ",
    },
    {
      id: "echo-workshop",
      title: "Echo Masterclass Ultrasound Workshop",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05"],
      time: "Journée (pro)",
      category: "conference",
      city: "Nice",
      venue: "Nice",
      address: "Nice",
      lat: 43.7105,
      lng: 7.2555,
      price: "Formation pro",
      free: false,
      description: "Atelier pratique échographie urgences / soins intensifs / anesthésie.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },

    {
      id: "quinzaine-seniors",
      title: "Quinzaine des Seniors — journée départementale",
      days: ["2026-10-05"],
      time: "9h–17h",
      category: "festival",
      city: "Nice",
      venue: "Palais de la Méditerranée — Salon Azur",
      address: "13 promenade des Anglais, Nice",
      lat: 43.6954,
      lng: 7.2658,
      price: "Gratuit",
      free: true,
      description: "Ouverture de la 3e Quinzaine : +25 stands (loisirs, droits, prévention), théâtre La retraite de Babeth, animations numériques. Jusqu'au 18 oct. dans le 06.",
      source: "departement06.fr",
      url: "https://www.departement06.fr/actualites/la-quinzaine-des-seniors-revient-en-2026",
    },
    {
      id: "maison-ia-fds",
      title: "Quand l'IA passe en cuisine — Village des Sciences",
      days: ["2026-10-05"],
      time: "17h–20h",
      category: "conference",
      city: "Biot",
      venue: "La Maison de l'IA — ALPHA Sophia Antipolis",
      address: "ALPHA Sophia Antipolis, Biot",
      lat: 43.6168,
      lng: 7.0552,
      price: "Gratuit (sur inscription)",
      free: true,
      description: "Inauguration Fête de la Science : ateliers IA, gastronomie et créativité numérique, apéritif et démonstrations.",
      source: "weezevent.com",
      url: "https://my.weezevent.com/fete-de-la-science-2026-la-maison-de-lia",
    },
    {
      id: "fete-science-06",
      title: "Fête de la Science 2026",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11"],
      time: "2–12 oct.",
      category: "festival",
      city: "Nice",
      venue: "Tout le département",
      address: "Alpes-Maritimes",
      lat: 43.7034,
      lng: 7.2663,
      price: "Gratuit (selon sites)",
      free: true,
      description: "35e édition : villages, ateliers, conférences — Nice, Villeneuve-Loubet, Mouans-Sartoux, Antibes, Biot…",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/lundi-5-octobre-2026-5-10-2026_JPJ",
    },
    {
      id: "anthea-poussez",
      title: "Poussez-vous les mecs",
      days: ["2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10"],
      time: "Selon séances",
      category: "theatre",
      city: "Antibes",
      venue: "anthéa",
      address: "260 av. Jules Grec, Antibes",
      lat: 43.5948,
      lng: 7.1105,
      price: "Tarifs anthéa",
      free: false,
      description: "Adaptation de Claire Bretécher — verve caustique et regard sur les rapports hommes-femmes.",
      source: "anthea-antibes.fr",
      url: "https://www.anthea-antibes.fr/fr/calendrier",
    },
    {
      id: "les-12-notes",
      title: "Les 12 notes",
      days: ["2026-10-07"],
      time: "14h30",
      category: "theatre",
      city: "Nice",
      venue: "Théâtre Francis Gag",
      address: "4 rue de la Croix, Nice",
      lat: 43.6978,
      lng: 7.2778,
      price: "8 €",
      free: false,
      description: "Ode comique à la musique : un élève timide et un pianiste acariâtre face à un monde un peu trop bruyant. Mise en scène Florent Chauvet.",
      source: "sortir06.fr",
      url: "https://www.sortir06.fr/agenda/par-mois/mercredi-7-octobre-2026-les-12-notes/",
    },
    {
      id: "tnn-saigon",
      title: "Saigon",
      days: ["2026-10-08", "2026-10-09"],
      time: "19h30",
      category: "theatre",
      city: "Nice",
      venue: "TNN — Salle de La Cuisine",
      address: "4-6 place Saint-François, Nice",
      lat: 43.6972,
      lng: 7.2768,
      price: "Billetterie TNN",
      free: false,
      description: "Caroline Guiela Nguyen — fresque familiale Vietnam–France (~3h20 avec entracte). Dès 15 ans.",
      source: "tnn.fr",
      url: "https://www.tnn.fr/fr/spectacles/saison-2026-2027/saigon",
    },
    {
      id: "israel-mohamed",
      title: "Israel & Mohamed",
      days: ["2026-10-08", "2026-10-09"],
      time: "20h",
      category: "danse",
      city: "Grasse",
      venue: "Théâtre de Grasse",
      address: "2 av. Maximin Isnard, Grasse",
      lat: 43.6582,
      lng: 6.9228,
      price: "Tarif spécial Grasse / TNN",
      free: false,
      description: "Duo flamenco & théâtre documentaire : Israel Galván et Mohamed El Khatib. Coréalisation TNN. Bord plateau le 8.",
      source: "theatredegrasse.com",
      url: "https://www.theatredegrasse.com/spectacle/israel-mohamed/",
    },
    {
      id: "louis-matute",
      title: "Jeudis du jazz — Louis Matute",
      days: ["2026-10-08"],
      time: "19h30",
      category: "concert",
      city: "Cannes",
      venue: "Théâtre Alexandre III",
      address: "19 bd Alexandre III, Cannes",
      lat: 43.5518,
      lng: 7.0172,
      price: "Selon billetterie",
      free: false,
      description: "Guitariste suisse — cycle Les jeudis du jazz.",
      source: "cannes.com",
      url: "https://www.cannes.com",
    },
    {
      id: "anthea-hasbeen",
      title: "Has been",
      days: ["2026-10-08", "2026-10-09"],
      time: "Selon séances",
      category: "danse",
      city: "Antibes",
      venue: "anthéa",
      address: "260 av. Jules Grec, Antibes",
      lat: 43.595,
      lng: 7.1102,
      price: "Tarifs anthéa",
      free: false,
      description: "Danse contemporaine — collaboration de deux figures majeures de la scène.",
      source: "anthea-antibes.fr",
      url: "https://www.anthea-antibes.fr/fr/calendrier",
    },
    {
      id: "enoch-arden",
      title: "Enoch Arden",
      days: ["2026-10-09"],
      time: "20h",
      category: "theatre",
      city: "Nice",
      venue: "TNN — Salle des Franciscains",
      address: "Nice",
      lat: 43.6975,
      lng: 7.2772,
      price: "Billetterie TNN",
      free: false,
      description: "D'après Tennyson, musique Richard Strauss — théâtre-musique (~1h10), dès 12 ans.",
      source: "tnn.fr",
      url: "https://www.tnn.fr/fr/calendrier/octobre/2026",
    },
    {
      id: "wackids",
      title: "The Wackids — Futur 2000",
      days: ["2026-10-09"],
      time: "19h30",
      category: "famille",
      city: "Cannes",
      venue: "Théâtre de la Licorne",
      address: "Cannes La Bocca",
      lat: 43.5512,
      lng: 6.9815,
      price: "Selon billetterie",
      free: false,
      description: "Concert-spectacle dès 6 ans — saison jeune public de la Licorne.",
      source: "cannes.com",
      url: "https://www.cannes.com",
    },
    {
      id: "nash-nice",
      title: "Nash — nouveau spectacle",
      days: ["2026-10-10"],
      time: "20h",
      category: "humour",
      city: "Nice",
      venue: "Théâtre Lino Ventura",
      address: "Nice",
      lat: 43.7055,
      lng: 7.2648,
      price: "34 €",
      free: false,
      description: "Stand-up intimiste sur la crise de la trentaine.",
      source: "06.agendaculturel.fr",
      url: "https://06.agendaculturel.fr/theatre/",
    },
    {
      id: "dame-pierre",
      title: "La Dame de Pierre",
      days: ["2026-10-10"],
      time: "20h45",
      category: "concert",
      city: "Nice",
      venue: "Palais Nikaïa",
      address: "163 bd René Cassin, Nice",
      lat: 43.6762,
      lng: 7.1998,
      price: "Selon billetterie",
      free: false,
      description: "Fresque musicale hommage à Notre-Dame de Paris — chants, danses, huit siècles d'histoire.",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/agenda/agenda-du-jour/samedi-10-octobre-2026-10-10-2026_JPJ",
    },
    {
      id: "heure-attendre",
      title: "Une heure à t'attendre",
      days: ["2026-10-10"],
      time: "20h30",
      category: "theatre",
      city: "Cannes",
      venue: "Théâtre Palais Stéphanie — JW Marriott",
      address: "Cannes",
      lat: 43.5498,
      lng: 7.0168,
      price: "Saison Palais des Festivals",
      free: false,
      description: "Thierry Frémont & Nicolas Vaude — saison des spectacles du Palais.",
      source: "cannes.com",
      url: "https://www.cannes.com/fr/agenda/evenements/saison-des-spectacles-du-palais-des-festivals-2026-2027/une-heure-a-t-attendre-thierry-fremont-et-nicolas-vaude.html",
    },
    {
      id: "tu-connais-chanson",
      title: "Tu connais la chanson ?",
      days: ["2026-10-10"],
      time: "20h",
      category: "humour",
      city: "Nice",
      venue: "Théâtre Francis Gag",
      address: "4 rue de la Croix, Nice",
      lat: 43.6978,
      lng: 7.2778,
      price: "Selon billetterie",
      free: false,
      description: "Stand-up poético-musical de Louis Caratini, Vieux-Nice.",
      source: "jds.fr",
      url: "https://www.jds.fr/nice/agenda/agenda-du-jour/samedi-10-octobre-2026-10-10-2026_JPJ",
    },
    {
      id: "exercices-style",
      title: "Exercices de style",
      days: ["2026-10-10"],
      time: "20h30",
      category: "theatre",
      city: "Nice",
      venue: "Nice",
      address: "Nice",
      lat: 43.7005,
      lng: 7.2688,
      price: "Selon billetterie",
      free: false,
      description: "Raymond Queneau : cinq comédiens, quarante personnages — humour et poésie des mots.",
      source: "20minutes.fr",
      url: "https://www.20minutes.fr/arts-stars/loisirs/4251230-20261005-alpes-maritimes-06-meilleures-sorties-activites-faire-5-octobre-11-octobre-2026",
    },
    {
      id: "agro-clown",
      title: "Agro le clown — ouverture Boeuf Théâtre",
      days: ["2026-10-10"],
      time: "18h",
      category: "famille",
      city: "Antibes",
      venue: "Place Nationale",
      address: "Place Nationale, Antibes",
      lat: 43.5806,
      lng: 7.1255,
      price: "Gratuit",
      free: true,
      description: "Spectacle de rue pour l'ouverture du Boeuf Théâtre (10–17 oct.) — rire et danse en famille.",
      source: "nicematin.com",
      url: "https://www.nicematin.com/culture/theatre/que-voir-ce-mois-ci-au-theatre-du-cote-d-antibes-cannes-et-de-grasse-10731043",
    },
    {
      id: "village-sciences-antibes",
      title: "Village des Sciences et de l'Innovation",
      days: ["2026-10-10", "2026-10-11"],
      time: "Journée",
      category: "festival",
      city: "Antibes",
      venue: "Antibes Juan-les-Pins",
      address: "Antibes",
      lat: 43.5804,
      lng: 7.1238,
      price: "Gratuit",
      free: true,
      description: "Fête de la Science — stands et ateliers grand public (Maison de l'IA partenaire).",
      source: "weezevent.com",
      url: "https://my.weezevent.com/fete-de-la-science-2026-la-maison-de-lia",
    },
    {
      id: "boeuf-theatre",
      title: "Boeuf Théâtre",
      days: ["2026-10-10", "2026-10-11"],
      time: "Jusqu'au 17 oct.",
      category: "festival",
      city: "Antibes",
      venue: "Fort Carré & scènes de la ville",
      address: "Antibes",
      lat: 43.5895,
      lng: 7.1288,
      price: "Selon spectacles",
      free: false,
      description: "Festival d'humour : L'impatient (14), L'excellence ordinaire (15), Je vis avec Freddy Mercury (16) au Fort Carré 20h30.",
      source: "nicematin.com",
      url: "https://www.nicematin.com/culture/theatre/que-voir-ce-mois-ci-au-theatre-du-cote-d-antibes-cannes-et-de-grasse-10731043",
    },
    {
      id: "comedy-club-bobar",
      title: "Comedy Club — Bobar",
      days: ["2026-10-02", "2026-10-03", "2026-10-09", "2026-10-10"],
      time: "Soirée (ven.)",
      category: "humour",
      city: "Nice",
      venue: "Bobar Comedy Club",
      address: "Nice",
      lat: 43.6995,
      lng: 7.2718,
      price: "Selon soirée",
      free: false,
      description: "Soirées stand-up — saison jusqu'en avril 2027.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/lundi-5-octobre-2026-5-10-2026_JPJ",
    },

    // ——— Expos (ouverts ces jours) ———
    {
      id: "expo-africa-pop",
      title: "Africa Pop — art naïf",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11"],
      time: "Horaires musée",
      category: "expo",
      city: "Nice",
      venue: "Musée Anatole Jakovsky",
      address: "Château Sainte-Hélène, Nice",
      lat: 43.6885,
      lng: 7.2185,
      price: "Tarif musée",
      free: false,
      description: "Exposition jusqu'au 18 octobre 2026.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "expo-chagall",
      title: "Musée Marc Chagall",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11"],
      time: "Horaires musée",
      category: "expo",
      city: "Nice",
      venue: "Musée National Marc Chagall",
      address: "Nice",
      lat: 43.7092,
      lng: 7.2695,
      price: "Tarif musée",
      free: false,
      description: "Plus grande collection publique d'œuvres de Chagall.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "expo-escoffier",
      title: "Auguste Escoffier, un humaniste",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11"],
      time: "Horaires musée",
      category: "expo",
      city: "Villeneuve-Loubet",
      venue: "Musée Escoffier",
      address: "Villeneuve-Loubet",
      lat: 43.6388,
      lng: 7.1215,
      price: "Tarif musée",
      free: false,
      description: "Exposition sur l'engagement social du grand chef.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/samedi-3-octobre-2026-3-10-2026_JPJ",
    },
    {
      id: "expo-lascaris",
      title: "Merveilles et curiosités",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11"],
      time: "Horaires musée",
      category: "expo",
      city: "Nice",
      venue: "Palais Lascaris",
      address: "15 rue Droite, Nice",
      lat: 43.6974,
      lng: 7.2774,
      price: "Tarif musée",
      free: false,
      description: "Cabinet de curiosités baroque jusqu'en janvier 2027.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/lundi-5-octobre-2026-5-10-2026_JPJ",
    },
    {
      id: "expo-maeght",
      title: "Ellsworth Kelly & Peter Knapp — Fondation Maeght",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11"],
      time: "Horaires fondation",
      category: "expo",
      city: "Saint-Paul-de-Vence",
      venue: "Fondation Maeght",
      address: "Saint-Paul-de-Vence",
      lat: 43.7006,
      lng: 7.1152,
      price: "Tarif fondation",
      free: false,
      description: "Aux bords de l'eau (Kelly) et Le temps Courrèges (Knapp).",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/lundi-5-octobre-2026-5-10-2026_JPJ",
    },
    {
      id: "expo-dirosa",
      title: "Mirages du monde — Hervé Di Rosa",
      days: ["2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06", "2026-10-07", "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11"],
      time: "Horaires musée",
      category: "expo",
      city: "Cannes",
      venue: "Cannes",
      address: "Cannes",
      lat: 43.5526,
      lng: 7.0174,
      price: "Selon lieu",
      free: false,
      description: "Peinture, sculpture, céramique — univers coloré jusqu'au 8 novembre.",
      source: "jds.fr",
      url: "https://www.jds.fr/alpes-maritimes/agenda/agenda-du-jour/lundi-5-octobre-2026-5-10-2026_JPJ",
    },
  ],
};
